services:
  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - "4001:4001"
      - "8080:8080"
      - "9099:9099"
      - "9199:9199"
    command: >
      firebase emulators:start
      --project demo-re-day
      --import=/workspace/.firebase-data
      --export-on-exit
